### ISSUE TITLE
Optional Show R Code in the Report

### ISSUE THREAD

**Issue by Polkas** [insightsengineering/teal.reporter#95] opened 2022-06-29 15:06 UTC
We should think about global and local switches in the Previewer so sb could decided if want to add the Show R Code into the Card. The SHow R Code could be easily very voluminous so it could be desirable to have such functionality.

**Comment by gogonzo** [comment] 2022-07-21 13:59
One global witch for all cards.

**Comment by Polkas** [comment] 2022-07-27 20:28
Please consider a new knitr functionality of ````{comment} chunks for turn off Show R Code

Or with `echo =` TRUE or FALSE (turn off with required functionality) and always eval = FALSE. 
We could paste the code directly to the chunk.

**Comment by nikolas-burkoff** [comment] 2022-08-25 14:04
Duplicate of #131

**Comment by donyunardi** [comment] 2022-11-19 00:38
Closing as duplicate.

**Closed by donyunardi** 2022-11-19 00:38 UTC
Labels: core
