### ISSUE TITLE
Report Buttons

### ISSUE THREAD

**Issue by npaszty** [insightsengineering/teal.reporter#105] opened 2022-07-06 00:20 UTC
### Feature description

when I maximize my window then the new reporter buttons line feed. 
would suggest having a short header like "Report Settings" and then under that "Add", "Download", "Reset" to save real estate.

![image](https://user-images.githubusercontent.com/40777373/177432875-00f70abf-2c67-4794-8063-91a0907a9e3f.png)

![image](https://user-images.githubusercontent.com/40777373/177437294-80a1c500-9a7c-409d-a4b4-d4aaf96bcc90.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by Polkas** [comment] 2022-07-06 08:08
Duplicate of the https://github.com/insightsengineering/teal.reporter/issues/88

**Closed by Polkas** 2022-07-06 08:08 UTC
Labels: enhancement
